; PlatformIO Project Configuration File
; TigerScale V2 - Dual RC522 + Servo

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_protocol = esptool
board_build.filesystem = littlefs
board_build.partitions = partitions.csv

lib_deps =
    tzapu/WiFiManager @ ^2.0.16-rc.2
    me-no-dev/ESPAsyncWebServer @ ^1.2.3
    me-no-dev/AsyncTCP @ ^1.1.1
    adafruit/Adafruit SSD1306 @ ^2.5.7
    adafruit/Adafruit GFX Library @ ^1.11.3
    bogde/HX711 @ ^0.7.5
    miguelbalboa/MFRC522 @ ^1.4.10
    bblanchon/ArduinoJson @ ^6.21.5
    madhephaestus/ESP32Servo @ ^3.0.5

build_flags =
    -D CONFIG_LITTLEFS_FOR_IDF_3_2
    -Os

upload_speed = 460800
monitor_speed = 115200
monitor_filters =
    esp32_exception_decoder
