#!/usr/bin/env bash
#
# update_toc.sh — Regenerate the Table of Contents at the top of src/main.cpp
#
# Scans for section banners — three consecutive comment lines like:
#   // ============================================================================
#   // §N — SECTION NAME      (the §N is optional; auto-renumbered if missing)
#   // ============================================================================
#
# …computes the line range of each section, and rewrites the TOC block so any
# AI agent (or human) can jump straight to the right area without loading the
# whole 3500-line file.
#
# Idempotent: running it multiple times produces the same output.
# Safe to run as a pre-commit hook.
#
# Usage:
#   ./scripts/update_toc.sh                 # update src/main.cpp
#   ./scripts/update_toc.sh path/to/file.cpp
#
# Token-saving rationale: with the TOC, an agent can:
#   Read(file, offset=N, limit=M)
# …to load only the relevant section instead of the whole file (~85% savings).

set -euo pipefail

# Find the repo root (script may be called from any directory)
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
TARGET="${1:-$REPO_ROOT/src/main.cpp}"

if [ ! -f "$TARGET" ]; then
    echo "❌ File not found: $TARGET" >&2
    exit 1
fi

PYTHON="$(command -v python3 || command -v python || true)"
if [ -z "$PYTHON" ]; then
    echo "❌ python3 required" >&2
    exit 1
fi

"$PYTHON" - "$TARGET" <<'PYEOF'
import re, sys
from pathlib import Path

TARGET = Path(sys.argv[1])
TOC_BEGIN = "// ─── TOC BEGIN (auto-generated by scripts/update_toc.sh) ───"
TOC_END   = "// ─── TOC END ───────────────────────────────────────────────"

src = TARGET.read_text(encoding="utf-8")
lines = src.splitlines(keepends=False)

# 1) Locate section banners. A banner is a "// ===…" line followed by a
#    "// TITLE" line, then another "// ===…". We capture (lineno, title).
BAR = re.compile(r"^// =+\s*$")
TITLE = re.compile(r"^// (.+?)\s*$")

sections = []  # list of (line_index_of_first_bar, title_clean)
i = 0
while i < len(lines) - 2:
    if BAR.match(lines[i]) and TITLE.match(lines[i + 1]) and BAR.match(lines[i + 2]):
        title = TITLE.match(lines[i + 1]).group(1).strip()
        # Skip uppercase-only sections that are obviously banners (we want them all)
        sections.append((i, title))
        i += 3
        continue
    i += 1

if not sections:
    print("⚠ No section banners found, nothing to do.", file=sys.stderr)
    sys.exit(0)

# 2) Renumber: §1 to §N. Strip any existing "§N — " prefix from titles.
clean = []
for idx, (line_no, title) in enumerate(sections, start=1):
    # Strip leading "§N — " or "§N - " or "§N. "
    clean_title = re.sub(r"^§\d+\s*[—\-:.]\s*", "", title).strip()
    clean.append((line_no, idx, clean_title))

# 3) Compute end-line of each section (= start of next section - 1, or EOF)
ranges = []
for k, (line_no, num, title) in enumerate(clean):
    next_start = clean[k + 1][0] if k + 1 < len(clean) else len(lines)
    # Section start is reported as line_no+1 (after the top bar) for human use
    ranges.append((num, title, line_no + 1, next_start))

# 4) Patch the section title lines IN-PLACE to add §N prefix
for line_no, num, title in clean:
    new_title = f"// §{num} — {title}"
    if lines[line_no + 1] != new_title:
        lines[line_no + 1] = new_title

# 5) Build the TOC block
max_title = max(len(t) for _, t, _, _ in ranges)
toc_lines = [TOC_BEGIN]
toc_lines.append("//")
toc_lines.append("//   TABLE OF CONTENTS                            line range")
toc_lines.append("//   ────────────────────────────────────────────  ──────────")
for num, title, start, end in ranges:
    label = f"§{num:<3}{title}"
    toc_lines.append(f"//   {label:<{max_title + 5}}  {start:>5}–{end:>5}")
toc_lines.append("//")
toc_lines.append("//   To regenerate this block:  ./scripts/update_toc.sh")
toc_lines.append(TOC_END)

# 6) Inject the TOC. We place it AFTER any leading /* … */ block-comment header,
#    but BEFORE the first #include. If a previous TOC block exists, replace it.
out = []
inserted = False

# Drop existing TOC block, plus the blank lines we wrap around it.
i = 0
while i < len(lines):
    if lines[i].strip().startswith(TOC_BEGIN):
        # Pop any blank line we already pushed JUST BEFORE the TOC marker —
        # we'll re-add it from the insertion code, so this avoids drift.
        while out and out[-1].strip() == "":
            out.pop()
        # Skip until matching TOC_END inclusive
        while i < len(lines) and not lines[i].strip().startswith(TOC_END):
            i += 1
        i += 1   # skip the END line itself
        # Skip ALL trailing blank lines that immediately follow the TOC
        while i < len(lines) and lines[i].strip() == "":
            i += 1
        continue
    out.append(lines[i])
    i += 1

lines = out
out = []

# Now insert TOC. Find the right spot.
i = 0
header_skipped = False
# Skip leading /* */ block comment if present
if i < len(lines) and lines[i].lstrip().startswith("/*"):
    while i < len(lines):
        out.append(lines[i])
        if "*/" in lines[i]:
            i += 1
            break
        i += 1
    header_skipped = True

# Skip trailing blank lines after header
while i < len(lines) and lines[i].strip() == "":
    out.append(lines[i])
    i += 1

# Insert the TOC here
out.append("")
out.extend(toc_lines)
out.append("")
inserted = True

# Append the rest unchanged
out.extend(lines[i:])

# 7) Write back, preserve trailing newline
new_src = "\n".join(out) + ("\n" if src.endswith("\n") else "")
if new_src != src:
    TARGET.write_text(new_src, encoding="utf-8")
    print(f"✓ TOC updated in {TARGET} ({len(ranges)} sections)")
else:
    print(f"✓ TOC already up-to-date in {TARGET}")
PYEOF
